### ISSUE TITLE
processor-info --help does not correctly describe -r function

### ISSUE THREAD

**Issue by jazzace** [autopkg/autopkg#807]
**Describe the problem**
`autopkg processor-info -h` states that the argument for the `-r` option should be "Name of recipe using the processor." This is incorrect advice in two different cases for non-core processors:
1. If the user specifies a recipe in the same directory as the processor, it succeeds, even if the recipe never calls the processor (e.g., stub recipe).
2. If the user specifies a recipe that calls the processor using the syntax for a shared processor (e.g., recipe_identifier/processor_name), it fails.

These are somewhat related to issue #696.

**AutoPkg output**
**%** autopkg processor-info -h
```
Usage: autopkg processor-info [options] processorname

Options:
  -h, --help            show this help message and exit
  --prefs=FILE_PATH     
  -r RECIPE, --recipe=RECIPE
                        Name of recipe using the processor.
  -d DIRECTORY, --search-dir=DIRECTORY
                        Directory to search for recipes. Can be specified
                        multiple times.
  --override-dir=DIRECTORY
                        Directory to search for recipe overrides. Can be
                        specified multiple times.
```
**%** autopkg processor-info JamfPackageUploader -r JamfUploaderProcessors.recipe.yaml
```
Description: A processor for AutoPkg that will upload a package to a JCDS or
    File Share Distribution Point.
    Can be run as a post-processor for a pkg recipe or in a child recipe.
    The pkg recipe must output pkg_path or this will fail.
Input variables:
 […]
```
Contents of JamfUploaderProcessors.recipe.yaml (from grahampugh-recipes, located in the same directory as JamfUploaderProcessors.recipe.yaml)
```
Description: Recipe stub for any Processors in this directory.
Identifier: com.github.grahampugh.jamf-upload.processors
Input: {}
MinimumVersion: "2.3"
Process: []
```
**%** autopkg processor-info JamfPackageUploader -r BBEdit.jamf.recipe.yaml
```
Unknown processor 'JamfPackageUploader'
```
Contents of BBEdit.jamf.recipe.yaml (recipe located in grahampugh-recipes and uses JamfPackageUploader but is in a different directory than the processor)
```
Comment: Recipe automatically generated from com.github.jss-recipes.jss.BBEdit by JamfRecipeMaker
Identifier: com.github.autopkg.grahampugh-recipes.jamf.BBEdit
ParentRecipe: com.github.autopkg.pkg.BBEdit
MinimumVersion: '2.3'

Input:
  NAME: BBEdit
  CATEGORY: Productivity
  GROUP_NAME: BBEdit-update-smart
  GROUP_TEMPLATE: JamfSmartGroupTemplate.xml
  TESTING_GROUP_NAME: Testing
  POLICY_CATEGORY: Testing
  POLICY_NAME: Install Latest %NAME%
  POLICY_TEMPLATE: JamfPolicyTemplate.xml
  SELF_SERVICE_DISPLAY_NAME: Install Latest %NAME%
  SELF_SERVICE_DESCRIPTION: BBEdit is the leading professional HTML and text editor for the Mac.
  SELF_SERVICE_ICON: '%NAME%.png'
  UPDATE_PREDICATE: pkg_uploaded == False

Process:
- Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
  Arguments:
    pkg_category: '%CATEGORY%'

[…]
```

**Expected behavior**
One of two things should happen:
1. All of these `processor-info` commands should succeed.
2. The `--help` should be rewritten to indicate how the option actually functions, e.g.,
```
  -r RECIPE, --recipe=RECIPE
                        Name of recipe located in the same directory as the processor.
```

**Version (please complete the following information):**
- OS version: 12.3.1
- AutoPkg Version: 2.3.1, 2.4.1
