### ISSUE TITLE
new-recipe verb creates non-compliant YAML

### ISSUE THREAD

**Issue by jazzace** [autopkg/autopkg#859]
**Describe the problem**
`autopkg new-recipe --format=yaml` generates a new recipe that is not precisely correct in syntax. While a recipe written this way may be tolerated by AutoPkg, some linters note that each Process step should begin with a - indented by two spaces (`new-recipe` uses 0 spaces).

**AutoPkg output**
`autopkg new-recipe --format=yaml newrecipe.check.recipe.yaml` generates the following file:
```
Description: Recipe description
Identifier: local.newrecipe
Input:
  NAME: newrecipe
MinimumVersion: '2.3'
Process:
- Arguments:
    Argument1: Value1
    Argument2: Value2
  Processor: ProcessorName
```

**Expected behaviour**
The file should be formatted thusly (note the extra 2 spaces indent in the Process dict):
```
Description: Recipe description
Identifier: local.newrecipe
Input:
  NAME: newrecipe
MinimumVersion: '2.3'
Process:
  - Arguments:
      Argument1: Value1
      Argument2: Value2
    Processor: ProcessorName
```

**Version (please complete the following information):**
 - OS version: macOS 13.4
- AutoPkg Version: 2.7.2
